//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstructor
    {
        public int InstructorId { get; set; }
        public string Name { get; set; }
        public string CourseTaught { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    }
}
